language: java
# use Java 8
jdk:
- oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

################
# CODACITY INTEGRATION (static code analysis)
################
# Requirement: configure TRAVIS build and add the codacity token as environment variable
#              export CODACY_PROJECT_TOKEN=%Project_Token%
