language: java
# no advanced feature: application should run for a simple user
sudo: false
# use Java 8
jdk:
- oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

################
# CODACITY INTEGRATION (static code analysis)
################
# Requirement: configure TRAVIS build and add the codacity token as environment variable
#              export CODACY_PROJECT_TOKEN=%Project_Token%


# Download latest codacity artifact
before_install:
  - sudo apt-get install jq
  - curl $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("application/x-java-archive"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar

# Public reports
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
